spring:
  application:
    name: Birthday
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: keshav_user
    password: keshav_pass
    driver-class-name: oracle.jdbc.OracleDriver
  security:
    user:
      name: user
      password: mypassword
  mail:
    host: smtp.gmail.com
    port: 587
    username: keshav.kapoor0801@gmail.com
    password: kqohjdkevggydkdb
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: smtp.gmail.com
          starttls:
              enable: true

server:
  port: 8081